// This will be a list of export consts. 

// GET_ERRORS
export const GET_ERRORS = 'GET_ERRORS';
// SET_CURRENT_USER
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
// GET_PROFILE
export const GET_PROFILE = 'GET_PROFILE';
// PROFILE_LOADING
export const PROFILE_LOADING = 'PROFILE_LOADING';
// PROFILE_NOT_FOUND
export const PROFILE_NOT_FOUND = 'PROFILE_NOT_FOUND';
// CLEAR_CURRENT_PROFILE
export const CLEAR_CURRENT_PROFILE = 'CLEAR_CURRENT_PROFILE';
// GET_PROFILES
export const GET_PROFILES = 'GET_PROFILES';